# 파일 규격 버전
version: "3.1"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  # 서비스 명
  mongodb:
    # 사용할 이미지
    image: mongo
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름 설정
    container_name: mongodb
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "27017:27017"
    # -e 옵션
    env_file: .env
    environment:
      # MongoDB 계정 및 패스워드 설정 옵션
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      # -v 옵션 (다렉토리 마운트 설정)
      - /data/mongodb/data/db:/data/db
      -
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_USERNAME: "${MARIADB_USERNAME}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - /data/mongodb/data/db:/data/db