import QueryProvider from '@/context/QueryProvider';
import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Nanum_Myeongjo } from 'next/font/google';
import RecoilProvider from '@/context/RecoilProvider';

const nanumFont = Nanum_Myeongjo({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={nanumFont.className}>
      <body className="w-full">
        <QueryProvider>
          <RecoilProvider>
            <main>{children}</main>
          </RecoilProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
